version: 0.2

phases:
  build:
    commands:
      # Login al ECR
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 596652342959.dkr.ecr.us-east-1.amazonaws.com
      
      # Construir la imagen Docker
      - echo Building the Docker image...
      - docker build -t app-cicd .
      
      # Etiquetar la imagen para ECR
      - echo Tagging the image...
      - docker tag app-cicd:latest 596652342959.dkr.ecr.us-east-1.amazonaws.com/app-cicd-repo:latest
      
      # Hacer push a ECR
      - echo Pushing the Docker image to ECR...
      - docker push 596652342959.dkr.ecr.us-east-1.amazonaws.com/app-cicd-repo/app-cicd-repo:latest

artifacts:
  files: '**/*'
  discard-paths: yes
